### ISSUE TITLE
No precompiled binaries present

### ISSUE THREAD

**Issue by Troynica** [harbaum/I2C-Tiny-USB#24]
Hello,

The readme mentions "If in doubt use the pre-compiled firmware.hex file distributed with the source code". However, I cannot find it. Is it not there or am I overlooking something? If it is not there, would it be possible to include it?

Kind regards,
Roy

**Comment by harbaum** [comment]
You are indeed right. I've added one to firmware/bin. This is untested as I don't have the flasher at hand. Please give feedback if it's working (or not).

 I've also updated the instructions to compile the firmware. This should now be easy to follow.

**Comment by Troynica** [comment]
Cool, it's there. If it's built from the current source, it should be working. I will let you know if it actually does when I receive ordered parts.

**Comment by Troynica** [comment]
I can confirm that it is working.
Thanks for all the effort !

**Comment by Troynica** [comment]
Let me close the issue because it is solved...
